# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee878ac336713b3f09bc998108fb86f7b3365b7a87b21ef91ead9c4a78c0358d81a1a2e6265812cd6fcb37bdd6fbf59057f4bb7f70c89b7edc6d5d107844135a

test:
  secret_key_base: 40b8b97e9e0f361758928a95dc070ede60ada95cab331720b24057e6ae9407a46adb50147ccd0cd95d921638c33a7b38c847ac2d22781fb282302d547e72438b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
